---
# Source: microservice/charts/mongodb/templates/sa-standalone.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-mongodb

---
# Source: microservice/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user

---
# Source: microservice/charts/mongodb/templates/svc-standalone.yaml

apiVersion: v1
kind: Service
metadata:
  name: user-mongodb
  labels:
    app: mongodb
    chart: mongodb-5.3.2
    release: "user"
    heritage: "Tiller"
spec:
  type: ClusterIP
  ports:
  - name: mongo
    port: 27017
    targetPort: mongodb
  selector:
    app: mongodb
    release: "user"

---
# Source: microservice/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app: user
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http-user
  selector:
    app: user

---
# Source: microservice/charts/mongodb/templates/deployment-standalone.yaml

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-mongodb
  labels:
    app: mongodb
    chart: mongodb-5.3.2
    release: "user"
    heritage: "Tiller"
spec:
  selector:
    matchLabels:
      app: mongodb
      release: "user"
  template:
    metadata:
      labels:
        app: mongodb
        release: "user"
        chart: mongodb-5.3.2
    spec:
      serviceAccountName: user-mongodb
      containers:
      - name: user-mongodb
        image: gcr.io/tetratelabs/modernbank/mongodb:4.0.6
        imagePullPolicy: "Always"
        env:
        - name: MONGODB_SYSTEM_LOG_VERBOSITY
          value: "0"
        - name: MONGODB_DISABLE_SYSTEM_LOG
          value: "no"
        - name: MONGODB_ENABLE_IPV6
          value: "yes"
        ports:
        - name: mongodb
          containerPort: 27017
        livenessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        volumeMounts:
        - name: data
          mountPath: /bitnami/mongodb
        resources:
          {}
          
      volumes:
      - name: data
        emptyDir: {}
---
# Source: microservice/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: user
  labels:
    app: user
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
        version: v1
    spec:
      serviceAccountName: user
      containers:
        - name: user
          image: "gcr.io/tetratelabs/modernbank/user:v1.0.0"
          imagePullPolicy: Always
          args: ["--port", "8080"]
          ports:
          - name: http
            containerPort: 8080

---
# Source: microservice/charts/mongodb/templates/configmap.yaml

---
# Source: microservice/charts/mongodb/templates/headless-svc-rs.yaml


---
# Source: microservice/charts/mongodb/templates/initialization-configmap.yaml

---
# Source: microservice/charts/mongodb/templates/poddisruptionbudget-arbiter-rs.yaml

---
# Source: microservice/charts/mongodb/templates/poddisruptionbudget-primary-rs.yaml

---
# Source: microservice/charts/mongodb/templates/poddisruptionbudget-secondary-rs.yaml


---
# Source: microservice/charts/mongodb/templates/prometheus-alerting-rule.yaml


---
# Source: microservice/charts/mongodb/templates/prometheus-service-monitor.yaml
      

---
# Source: microservice/charts/mongodb/templates/pvc-standalone.yaml

---
# Source: microservice/charts/mongodb/templates/secrets.yaml


---
# Source: microservice/charts/mongodb/templates/statefulset-arbiter-rs.yaml


---
# Source: microservice/charts/mongodb/templates/statefulset-primary-rs.yaml


---
# Source: microservice/charts/mongodb/templates/statefulset-secondary-rs.yaml


---
# Source: microservice/charts/mongodb/templates/svc-primary-rs.yaml


